name: Build

on:
  push:
    branches:
      - '**'
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.102'

      - name: Build
        run: ./build.sh

      - uses: actions/upload-artifact@v2-preview
        with:
          name: Create nupkg
          path: .publish/*.nupkg
